
name: GH Pages

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    # configure the environment
    - uses: actions/checkout@v2
    - uses: denoland/setup-deno@v1
      with:
        deno-version: v1.x    
    - name: rust-toolchain
      uses: actions-rs/toolchain@v1.0.6
      with:
        toolchain: nightly
        target: wasm32-unknown-unknown
    - name: setup-dioxus-cli
      run: |
        cargo install dioxus-cli

    # build css and rust
    - name: build css
      run: |
        deno run build_css
    - name: builds dioxus
      run: |
        rustup override set nightly
        dx build --release --platform=web

    # deploy for github.io
    - name: GitHub Pages action
      uses: peaceiris/actions-gh-pages@v3.7.3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_branch: gh-pages
        publish_dir: dist
        # cname: abex.dev
